### ISSUE TITLE
TypeError: forward() takes from 3 to 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by lxh666666** [zshanggu/HTRPN#4]
Traceback (most recent call last):
  File "/home/lee/software/HTRPN-main/tools/train_net.py", line 123, in <module>
    launch(
  File "/home/lee/software/HTRPN-main/fsdet/engine/launch.py", line 52, in launch
    main_func(*args)
  File "/home/lee/software/HTRPN-main/tools/train_net.py", line 117, in main
    return trainer.train()
  File "/home/lee/software/HTRPN-main/fsdet/engine/defaults.py", line 398, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/lee/software/HTRPN-main/fsdet/engine/train_loop.py", line 132, in train
    self.run_step(self.iter)
  File "/home/lee/software/HTRPN-main/fsdet/engine/train_loop.py", line 213, in run_step
    loss_dict = self.model(data, alg_iter)
  File "/home/lee/anaconda3/envs/HTRPN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lee/software/HTRPN-main/fsdet/modeling/meta_arch/rcnn.py", line 390, in forward
    proposals, for_calculate_loss = self.proposal_generator(images, features, gt_instances, batched_inputs)
  File "/home/lee/anaconda3/envs/HTRPN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes from 3 to 4 positional arguments but 5 were given
Train with COCO encounters this problem,  Do you know what the problem is, thank you very much！！！

**Comment by qjh666888** [comment]
请问你解决了嘛

**Comment by qjh666888** [comment]
> Traceback (most recent call last): File "/home/lee/software/HTRPN-main/tools/train_net.py", line 123, in launch( File "/home/lee/software/HTRPN-main/fsdet/engine/launch.py", line 52, in launch main_func(*args) File "/home/lee/software/HTRPN-main/tools/train_net.py", line 117, in main return trainer.train() File "/home/lee/software/HTRPN-main/fsdet/engine/defaults.py", line 398, in train super().train(self.start_iter, self.max_iter) File "/home/lee/software/HTRPN-main/fsdet/engine/train_loop.py", line 132, in train self.run_step(self.iter) File "/home/lee/software/HTRPN-main/fsdet/engine/train_loop.py", line 213, in run_step loss_dict = self.model(data, alg_iter) File "/home/lee/anaconda3/envs/HTRPN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in **call** result = self.forward(*input, **kwargs) File "/home/lee/software/HTRPN-main/fsdet/modeling/meta_arch/rcnn.py", line 390, in forward proposals, for_calculate_loss = self.proposal_generator(images, features, gt_instances, batched_inputs) File "/home/lee/anaconda3/envs/HTRPN/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in **call** result = self.forward(*input, **kwargs) TypeError: forward() takes from 3 to 4 positional arguments but 5 were given Train with COCO encounters this problem, Do you know what the problem is, thank you very much！！！

请问您有解决嘛？我现在也遇到了

**Comment by qjh666888** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zeyu ***@***.***&gt;; 
发送时间: 2024年5月9日(星期四) 晚上8:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zshanggu/HTRPN] TypeError: forward() takes from 3 to 4 positional arguments but 5 were given (Issue #4)














 
Thanks for your inquiry, can I see the config files you are using?
感谢您的询问，我可以看到您正在使用的配置文件吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
直接回复此电子邮件，在 GitHub 上查看或取消订阅。
You are receiving this because you commented.
您收到此消息是因为您发表了评论。  Message ID: ***@***.***&gt;

**Comment by qjh666888** [comment]
![image](https://github.com/zshanggu/HTRPN/assets/73637597/458813eb-0121-4a00-b392-b28b9f98de34)

**Comment by qjh666888** [comment]
> Thanks for your inquiry, can I see the config files you are using?

10shot_CL_IoU  can run, but 1shot_baseline cannot.

**Comment by zshanggu** [comment]
Thank you. You have to make sure your config file for 1shot comply with the form in the 10shot config files.
For example, you should confirm you have the below items:
```
PROPOSAL_GENERATOR:
    NAME: "TernaryHiercRPN"

...

ROI_HEADS:
    NAME: "TernaryHiercContraROIHeads"
```

**Comment by qjh666888** [comment]
PROPOSAL_GENERATOR       POTENTIAL_THRESHOLD: 0.5  #Do we need to modify it to 0.75
 



I also want to ask what x101 and tau are, and why the names of 1shot and 3shot are different.
What&nbsp;PascalVOC-detection are？

How should I modify the learning rate and iter if I use 1 gup and batch to 2.
I would greatly appreciate it if I could receive your reply



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zeyu ***@***.***&gt;; 
发送时间: 2024年5月9日(星期四) 晚上9:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zshanggu/HTRPN] TypeError: forward() takes from 3 to 4 positional arguments but 5 were given (Issue #4)














 
Thank you. You have to make sure your config file for 1shot comply with the form in the 10shot config files.
 For example, you should confirm you have the below items:
 PROPOSAL_GENERATOR:     NAME: "TernaryHiercRPN" ... ROI_HEADS:     NAME: "TernaryHiercContraROIHeads"

**Comment by qjh666888** [comment]
Do 1shot and 3shot need to be the same except for different sample sizes




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zeyu ***@***.***&gt;; 
发送时间: 2024年5月9日(星期四) 晚上9:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zshanggu/HTRPN] TypeError: forward() takes from 3 to 4 positional arguments but 5 were given (Issue #4)














 
Thank you. You have to make sure your config file for 1shot comply with the form in the 10shot config files.
 For example, you should confirm you have the below items:
 PROPOSAL_GENERATOR:     NAME: "TernaryHiercRPN" ... ROI_HEADS:     NAME: "TernaryHiercContraROIHeads"

**Comment by zshanggu** [comment]
Yes you can modify POTENTIAL_THRESHOLD.
I am not using X101 and tau, and you can ignore PascalVOC-detection.
You can go configs/Base-RCNN-FPN.yaml to modify your learning rate. I suggest to use batch-size of 0.01, just make sure you've load the correct pre-training weights, and then you are good to go.
The 5/10shot config files are good templates for you to use, just make all your config files follow their setting, and then it will work.

**Comment by qjh666888** [comment]
May I check your training logs for basic training and fine-tuning stages?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zshanggu/HTRPN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月9日(星期四) 晚上9:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zshanggu/HTRPN] TypeError: forward() takes from 3 to 4 positional arguments but 5 were given (Issue #4)





 
Yes you can modify POTENTIAL_THRESHOLD.
 I am not using X101 and tau, and you can ignore PascalVOC-detection.
 You can go configs/Base-RCNN-FPN.yaml to modify your learning rate. I suggest to use batch-size of 0.01, just make sure you've load the correct pre-training weights, and then you are good to go.
 The 5/10shot config files are good templates for you to use, just make all your config files follow their setting, and then it will work.

**Comment by zshanggu** [comment]
I don't hold them with me at this moment, but I can help you check what's going on with your training.

**Comment by qjh666888** [comment]
I am currently in the basic training stage. After the training is over, will my results be the same as yours? This can verify whether my hyperparameters are set correctly.So I can set the parameters for my fine-tuning stage。


Is 78.9 the result of basic training? Or 80.7




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zeyu ***@***.***&gt;; 
发送时间: 2024年5月9日(星期四) 晚上10:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zshanggu/HTRPN] TypeError: forward() takes from 3 to 4 positional arguments but 5 were given (Issue #4)















我现在不抱着他们，但我可以帮你检查一下你的训练是怎么回事。

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
你收到这个是因为你发表了评论。消息ID:< zshanggu / HTRPN /议题/ 4 / ***@***.***和&gt;

**Comment by qjh666888** [comment]
Because my batch is set to 2, my iter has increased. Currently, I am directly scaling 18000 * 8 because the batch has been reduced by 8 times, and lr is also divided by 8 because I only used 1 gup. At present, the effect is not known, and it may be troublesome for you in the future. Please forgive me




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zeyu ***@***.***&gt;; 
发送时间: 2024年5月9日(星期四) 晚上10:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zshanggu/HTRPN] TypeError: forward() takes from 3 to 4 positional arguments but 5 were given (Issue #4)














 
Ideally you may get 78 to 81 for the base training stage with no more than 10,000 iterations, the result may slightly varies depend on your hyperparameters.

**Comment by zshanggu** [comment]
No worry, since the new version of this paper is still under review, after that I will also open source all my model files.

**Comment by qjh666888** [comment]
What should I do when I use 1shot to reproduce in 8gup 16batch and cannot achieve the accuracy of the paper, which is about 10 points lower

> No worry, since the new version of this paper is still under review, after that I will also open source all my model files.不用担心，由于本文的新版本仍在审查中，之后我还将开源我所有的模型文件。

**Comment by Yupeipeipei** [comment]
> What should I do when I use 1shot to reproduce in 8gup 16batch and cannot achieve the accuracy of the paper, which is about 10 points lower
> 
> > No worry, since the new version of this paper is still under review, after that I will also open source all my model files.不用担心，由于本文的新版本仍在审查中，之后我还将开源我所有的模型文件。

I want to ask how you solved it

**Comment by wuwu362** [comment]
> What should I do when I use 1shot to reproduce in 8gup 16batch and cannot achieve the accuracy of the paper, which is about 10 points lower
> 
> > No worry, since the new version of this paper is still under review, after that I will also open source all my model files.不用担心，由于本文的新版本仍在审查中，之后我还将开源我所有的模型文件。

I want to ask how you solved it
